name: Build lume-epics

on:
  push:
    branches:
      - reg-test-setup
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.7, 3.8]
    name: Python ${{ matrix.python-version }}, ${{ matrix.os }} build
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          yes | pip install -r requirements.txt
          yes | pip install -r test-requirements.txt
          pip install .
          pytest --pyargs pyemittance


          
